pipeline:
  name: DevOps
  identifier: DevOps
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: DevopsBasics
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: warfile
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: awsconnector
                    region: eu-north-1
                    bucket: aws32bucket1
                    sourcePath: /harness/target/webapp-1.war
            "":
              type: S3Upload
              name: S3Upload_1
              identifier: S3Upload_1
              spec:
                connectorRef: awsconnector
                region: us-east-1
                bucket: aws32s3bucket
                sourcePath: /harness/target/webapp-1.war
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: fetch_Artifacts
            serviceInputs:
              serviceDefinition:
                type: Ssh
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: QA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tomcat
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          sudo su -
                          cd /
                          cd opt/tomcat/bin
                          ./startup.sh

                          docker start ddde2fc7e1a4
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Command
                  name: Command_1
                  identifier: Command_1
                  spec:
                    onDelegate: false
                    environmentVariables: []
                    outputVariables: []
                    commandUnits:
                      - identifier: copyartifact
                        name: copyartifact
                        type: DownloadArtifact
                        spec:
                          destinationPath: /opt/tomcat/webapps
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
